// Package contract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package contract

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ConnectionResultResult.
const (
	Connecting ConnectionResultResult = "connecting"
	Fail       ConnectionResultResult = "fail"
	Success    ConnectionResultResult = "success"
)

// Defines values for QueryExecResponseStatus.
const (
	Failed  QueryExecResponseStatus = "failed"
	Running QueryExecResponseStatus = "running"
)

// Configuration defines model for Configuration.
type Configuration struct {
	Database string          `json:"database"`
	Host     *string         `json:"host"`
	Name     string          `json:"name"`
	Password *PasswordConfig `json:"password,omitempty"`
	Port     *int            `json:"port"`
	Type     string          `json:"type"`
	Username *string         `json:"username"`
}

// ConfigurationsResponse defines model for ConfigurationsResponse.
type ConfigurationsResponse struct {
	Connections []Configuration `json:"connections"`
}

// ConnectionRequest defines model for ConnectionRequest.
type ConnectionRequest struct {
	ConfigurationName string `json:"configurationName"`
}

// ConnectionResult defines model for ConnectionResult.
type ConnectionResult struct {
	Result      ConnectionResultResult `json:"result"`
	UserMessage *string                `json:"userMessage"`
}

// ConnectionResultResult defines model for ConnectionResult.Result.
type ConnectionResultResult string

// ErrorPayload defines model for ErrorPayload.
type ErrorPayload struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// Node defines model for Node.
type Node struct {
	Attributes map[string]interface{} `json:"attributes"`
	Edges      map[string]NodeEdge    `json:"edges"`
	Id         string                 `json:"id"`
	Name       string                 `json:"name"`
	Type       string                 `json:"type"`
}

// NodeEdge defines model for NodeEdge.
type NodeEdge struct {
	Items     []string `json:"items"`
	Truncated bool     `json:"truncated"`
}

// NodesResponse defines model for NodesResponse.
type NodesResponse struct {
	Nodes []Node `json:"nodes"`
}

// PasswordConfig defines model for PasswordConfig.
type PasswordConfig struct {
	Key  string `json:"key"`
	Type string `json:"type"`
}

// QueryExecOptions defines model for QueryExecOptions.
type QueryExecOptions struct {
	MaxRows *int `json:"maxRows,omitempty"`
}

// QueryExecRequest defines model for QueryExecRequest.
type QueryExecRequest struct {
	ConfigurationName string                   `json:"configurationName"`
	Options           *QueryExecOptions        `json:"options,omitempty"`
	Params            *QueryExecRequest_Params `json:"params,omitempty"`
	Query             string                   `json:"query"`
}

// QueryExecRequestParams0 defines model for .
type QueryExecRequestParams0 map[string]interface{}

// QueryExecRequestParams1 defines model for .
type QueryExecRequestParams1 = []interface{}

// QueryExecRequest_Params defines model for QueryExecRequest.Params.
type QueryExecRequest_Params struct {
	union json.RawMessage
}

// QueryExecResponse defines model for QueryExecResponse.
type QueryExecResponse struct {
	JobId   string                  `json:"jobId"`
	Message *string                 `json:"message"`
	Status  QueryExecResponseStatus `json:"status"`
}

// QueryExecResponseStatus defines model for QueryExecResponse.Status.
type QueryExecResponseStatus string

// QueryResultColumn defines model for QueryResultColumn.
type QueryResultColumn struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

// QueryResultResponse defines model for QueryResultResponse.
type QueryResultResponse struct {
	Columns   []QueryResultColumn `json:"columns"`
	RowCount  int                 `json:"rowCount"`
	Rows      [][]interface{}     `json:"rows"`
	Truncated bool                `json:"truncated"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = ErrorPayload

// GetNodesParams defines parameters for GetNodes.
type GetNodesParams struct {
	// NodeId Optional repeated parameter limiting the nodes returned
	NodeId *[]string `form:"nodeId,omitempty" json:"nodeId,omitempty"`
}

// GetQueryResultParams defines parameters for GetQueryResult.
type GetQueryResultParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// StartConnectionJSONRequestBody defines body for StartConnection for application/json ContentType.
type StartConnectionJSONRequestBody = ConnectionRequest

// ExecQueryJSONRequestBody defines body for ExecQuery for application/json ContentType.
type ExecQueryJSONRequestBody = QueryExecRequest

// AsQueryExecRequestParams0 returns the union data inside the QueryExecRequest_Params as a QueryExecRequestParams0
func (t QueryExecRequest_Params) AsQueryExecRequestParams0() (QueryExecRequestParams0, error) {
	var body QueryExecRequestParams0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQueryExecRequestParams0 overwrites any union data inside the QueryExecRequest_Params as the provided QueryExecRequestParams0
func (t *QueryExecRequest_Params) FromQueryExecRequestParams0(v QueryExecRequestParams0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQueryExecRequestParams0 performs a merge with any union data inside the QueryExecRequest_Params, using the provided QueryExecRequestParams0
func (t *QueryExecRequest_Params) MergeQueryExecRequestParams0(v QueryExecRequestParams0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQueryExecRequestParams1 returns the union data inside the QueryExecRequest_Params as a QueryExecRequestParams1
func (t QueryExecRequest_Params) AsQueryExecRequestParams1() (QueryExecRequestParams1, error) {
	var body QueryExecRequestParams1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQueryExecRequestParams1 overwrites any union data inside the QueryExecRequest_Params as the provided QueryExecRequestParams1
func (t *QueryExecRequest_Params) FromQueryExecRequestParams1(v QueryExecRequestParams1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQueryExecRequestParams1 performs a merge with any union data inside the QueryExecRequest_Params, using the provided QueryExecRequestParams1
func (t *QueryExecRequest_Params) MergeQueryExecRequestParams1(v QueryExecRequestParams1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t QueryExecRequest_Params) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *QueryExecRequest_Params) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListConfigurations request
	ListConfigurations(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetNodes request
	GetNodes(ctx context.Context, configurationName string, params *GetNodesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StartConnectionWithBody request with any body
	StartConnectionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	StartConnection(ctx context.Context, body StartConnectionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StreamEvents request
	StreamEvents(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ExecQueryWithBody request with any body
	ExecQueryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ExecQuery(ctx context.Context, body ExecQueryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetQueryResult request
	GetQueryResult(ctx context.Context, jobId string, params *GetQueryResultParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListConfigurations(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListConfigurationsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetNodes(ctx context.Context, configurationName string, params *GetNodesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetNodesRequest(c.Server, configurationName, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StartConnectionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStartConnectionRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StartConnection(ctx context.Context, body StartConnectionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStartConnectionRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StreamEvents(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStreamEventsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExecQueryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExecQueryRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExecQuery(ctx context.Context, body ExecQueryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExecQueryRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetQueryResult(ctx context.Context, jobId string, params *GetQueryResultParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetQueryResultRequest(c.Server, jobId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListConfigurationsRequest generates requests for ListConfigurations
func NewListConfigurationsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/configurations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetNodesRequest generates requests for GetNodes
func NewGetNodesRequest(server string, configurationName string, params *GetNodesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "configurationName", runtime.ParamLocationPath, configurationName)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/configurations/%s/nodes", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.NodeId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "nodeId", runtime.ParamLocationQuery, *params.NodeId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewStartConnectionRequest calls the generic StartConnection builder with application/json body
func NewStartConnectionRequest(server string, body StartConnectionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewStartConnectionRequestWithBody(server, "application/json", bodyReader)
}

// NewStartConnectionRequestWithBody generates requests for StartConnection with any type of body
func NewStartConnectionRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/connections")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewStreamEventsRequest generates requests for StreamEvents
func NewStreamEventsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/events")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewExecQueryRequest calls the generic ExecQuery builder with application/json body
func NewExecQueryRequest(server string, body ExecQueryJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewExecQueryRequestWithBody(server, "application/json", bodyReader)
}

// NewExecQueryRequestWithBody generates requests for ExecQuery with any type of body
func NewExecQueryRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/queries")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetQueryResultRequest generates requests for GetQueryResult
func NewGetQueryResultRequest(server string, jobId string, params *GetQueryResultParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "jobId", runtime.ParamLocationPath, jobId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/queries/%s/result", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListConfigurationsWithResponse request
	ListConfigurationsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListConfigurationsResponse, error)

	// GetNodesWithResponse request
	GetNodesWithResponse(ctx context.Context, configurationName string, params *GetNodesParams, reqEditors ...RequestEditorFn) (*GetNodesResponse, error)

	// StartConnectionWithBodyWithResponse request with any body
	StartConnectionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*StartConnectionResponse, error)

	StartConnectionWithResponse(ctx context.Context, body StartConnectionJSONRequestBody, reqEditors ...RequestEditorFn) (*StartConnectionResponse, error)

	// StreamEventsWithResponse request
	StreamEventsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*StreamEventsResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// ExecQueryWithBodyWithResponse request with any body
	ExecQueryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExecQueryResponse, error)

	ExecQueryWithResponse(ctx context.Context, body ExecQueryJSONRequestBody, reqEditors ...RequestEditorFn) (*ExecQueryResponse, error)

	// GetQueryResultWithResponse request
	GetQueryResultWithResponse(ctx context.Context, jobId string, params *GetQueryResultParams, reqEditors ...RequestEditorFn) (*GetQueryResultResponse, error)
}

type ListConfigurationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ConfigurationsResponse
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListConfigurationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListConfigurationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetNodesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NodesResponse
	JSON404      *ErrorPayload
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetNodesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetNodesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type StartConnectionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *ConnectionResult
	JSON404      *ErrorPayload
	JSON409      *ErrorPayload
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r StartConnectionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StartConnectionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type StreamEventsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r StreamEventsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StreamEventsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ExecQueryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *QueryExecResponse
	JSON404      *ErrorPayload
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ExecQueryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ExecQueryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetQueryResultResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *QueryResultResponse
	JSON404      *ErrorPayload
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetQueryResultResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetQueryResultResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListConfigurationsWithResponse request returning *ListConfigurationsResponse
func (c *ClientWithResponses) ListConfigurationsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListConfigurationsResponse, error) {
	rsp, err := c.ListConfigurations(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListConfigurationsResponse(rsp)
}

// GetNodesWithResponse request returning *GetNodesResponse
func (c *ClientWithResponses) GetNodesWithResponse(ctx context.Context, configurationName string, params *GetNodesParams, reqEditors ...RequestEditorFn) (*GetNodesResponse, error) {
	rsp, err := c.GetNodes(ctx, configurationName, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetNodesResponse(rsp)
}

// StartConnectionWithBodyWithResponse request with arbitrary body returning *StartConnectionResponse
func (c *ClientWithResponses) StartConnectionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*StartConnectionResponse, error) {
	rsp, err := c.StartConnectionWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStartConnectionResponse(rsp)
}

func (c *ClientWithResponses) StartConnectionWithResponse(ctx context.Context, body StartConnectionJSONRequestBody, reqEditors ...RequestEditorFn) (*StartConnectionResponse, error) {
	rsp, err := c.StartConnection(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStartConnectionResponse(rsp)
}

// StreamEventsWithResponse request returning *StreamEventsResponse
func (c *ClientWithResponses) StreamEventsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*StreamEventsResponse, error) {
	rsp, err := c.StreamEvents(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStreamEventsResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// ExecQueryWithBodyWithResponse request with arbitrary body returning *ExecQueryResponse
func (c *ClientWithResponses) ExecQueryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExecQueryResponse, error) {
	rsp, err := c.ExecQueryWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExecQueryResponse(rsp)
}

func (c *ClientWithResponses) ExecQueryWithResponse(ctx context.Context, body ExecQueryJSONRequestBody, reqEditors ...RequestEditorFn) (*ExecQueryResponse, error) {
	rsp, err := c.ExecQuery(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExecQueryResponse(rsp)
}

// GetQueryResultWithResponse request returning *GetQueryResultResponse
func (c *ClientWithResponses) GetQueryResultWithResponse(ctx context.Context, jobId string, params *GetQueryResultParams, reqEditors ...RequestEditorFn) (*GetQueryResultResponse, error) {
	rsp, err := c.GetQueryResult(ctx, jobId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetQueryResultResponse(rsp)
}

// ParseListConfigurationsResponse parses an HTTP response from a ListConfigurationsWithResponse call
func ParseListConfigurationsResponse(rsp *http.Response) (*ListConfigurationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListConfigurationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ConfigurationsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetNodesResponse parses an HTTP response from a GetNodesWithResponse call
func ParseGetNodesResponse(rsp *http.Response) (*GetNodesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetNodesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NodesResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorPayload
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseStartConnectionResponse parses an HTTP response from a StartConnectionWithResponse call
func ParseStartConnectionResponse(rsp *http.Response) (*StartConnectionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StartConnectionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest ConnectionResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorPayload
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorPayload
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseStreamEventsResponse parses an HTTP response from a StreamEventsWithResponse call
func ParseStreamEventsResponse(rsp *http.Response) (*StreamEventsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StreamEventsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseExecQueryResponse parses an HTTP response from a ExecQueryWithResponse call
func ParseExecQueryResponse(rsp *http.Response) (*ExecQueryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ExecQueryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest QueryExecResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorPayload
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetQueryResultResponse parses an HTTP response from a GetQueryResultWithResponse call
func ParseGetQueryResultResponse(rsp *http.Response) (*GetQueryResultResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetQueryResultResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest QueryResultResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorPayload
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
