// Package contract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package contract

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ColumnNodeType.
const (
	Column ColumnNodeType = "column"
)

// Defines values for ConnectionResultResult.
const (
	Connecting ConnectionResultResult = "connecting"
	Fail       ConnectionResultResult = "fail"
	Success    ConnectionResultResult = "success"
)

// Defines values for ConstraintNodeType.
const (
	Constraint ConstraintNodeType = "constraint"
)

// Defines values for DatabaseNodeType.
const (
	Database DatabaseNodeType = "database"
)

// Defines values for IndexNodeType.
const (
	Index IndexNodeType = "index"
)

// Defines values for PasswordConfigType.
const (
	Keychain  PasswordConfigType = "keychain"
	PlainText PasswordConfigType = "plain_text"
	Shell     PasswordConfigType = "shell"
)

// Defines values for QueryExecResponseStatus.
const (
	Failed  QueryExecResponseStatus = "failed"
	Running QueryExecResponseStatus = "running"
)

// Defines values for SchemaNodeType.
const (
	Schema SchemaNodeType = "schema"
)

// Defines values for TableNodeType.
const (
	Table TableNodeType = "table"
)

// Defines values for TriggerNodeType.
const (
	Trigger TriggerNodeType = "trigger"
)

// Defines values for ViewNodeType.
const (
	View ViewNodeType = "view"
)

// ColumnNode defines model for ColumnNode.
type ColumnNode struct {
	Attributes ColumnNodeAttributes `json:"attributes"`
	Edges      map[string]NodeEdge  `json:"edges"`
	Id         string               `json:"id"`
	Name       string               `json:"name"`
	Type       ColumnNodeType       `json:"type"`
}

// ColumnNodeType defines model for ColumnNode.Type.
type ColumnNodeType string

// ColumnNodeAttributes defines model for ColumnNodeAttributes.
type ColumnNodeAttributes struct {
	CharMaxLength      *int64  `json:"charMaxLength,omitempty"`
	Column             string  `json:"column"`
	Connection         string  `json:"connection"`
	DataType           string  `json:"dataType"`
	DefaultValue       *string `json:"defaultValue,omitempty"`
	NotNull            bool    `json:"notNull"`
	NumericPrecision   *int64  `json:"numericPrecision,omitempty"`
	NumericScale       *int64  `json:"numericScale,omitempty"`
	Ordinal            int     `json:"ordinal"`
	PrimaryKeyPosition *int    `json:"primaryKeyPosition,omitempty"`
	Table              string  `json:"table"`
}

// Configuration defines model for Configuration.
type Configuration struct {
	Database string          `json:"database"`
	Host     *string         `json:"host"`
	Name     string          `json:"name"`
	Password *PasswordConfig `json:"password,omitempty"`
	Port     *int            `json:"port"`
	Tls      *TlsConfig      `json:"tls,omitempty"`
	Type     string          `json:"type"`
	Username *string         `json:"username"`
}

// ConfigurationsResponse defines model for ConfigurationsResponse.
type ConfigurationsResponse struct {
	Connections []Configuration `json:"connections"`
}

// ConnectionRequest defines model for ConnectionRequest.
type ConnectionRequest struct {
	ConfigurationName string `json:"configurationName"`
}

// ConnectionResult defines model for ConnectionResult.
type ConnectionResult struct {
	Result      ConnectionResultResult `json:"result"`
	UserMessage *string                `json:"userMessage"`
}

// ConnectionResultResult defines model for ConnectionResult.Result.
type ConnectionResultResult string

// ConstraintNode defines model for ConstraintNode.
type ConstraintNode struct {
	Attributes ConstraintNodeAttributes `json:"attributes"`
	Edges      map[string]NodeEdge      `json:"edges"`
	Id         string                   `json:"id"`
	Name       string                   `json:"name"`
	Type       ConstraintNodeType       `json:"type"`
}

// ConstraintNodeType defines model for ConstraintNode.Type.
type ConstraintNodeType string

// ConstraintNodeAttributes defines model for ConstraintNodeAttributes.
type ConstraintNodeAttributes struct {
	CheckClause        *string   `json:"checkClause,omitempty"`
	Columns            *[]string `json:"columns,omitempty"`
	Connection         string    `json:"connection"`
	ConstraintName     string    `json:"constraintName"`
	ConstraintType     string    `json:"constraintType"`
	IndexName          *string   `json:"indexName,omitempty"`
	Match              *string   `json:"match,omitempty"`
	OnDelete           *string   `json:"onDelete,omitempty"`
	OnUpdate           *string   `json:"onUpdate,omitempty"`
	ReferencedColumns  *[]string `json:"referencedColumns,omitempty"`
	ReferencedDatabase *string   `json:"referencedDatabase,omitempty"`
	ReferencedSchema   *string   `json:"referencedSchema,omitempty"`
	ReferencedTable    *string   `json:"referencedTable,omitempty"`
	Table              string    `json:"table"`
}

// DatabaseNode defines model for DatabaseNode.
type DatabaseNode struct {
	Attributes DatabaseNodeAttributes `json:"attributes"`
	Edges      map[string]NodeEdge    `json:"edges"`
	Id         string                 `json:"id"`
	Name       string                 `json:"name"`
	Type       DatabaseNodeType       `json:"type"`
}

// DatabaseNodeType defines model for DatabaseNode.Type.
type DatabaseNodeType string

// DatabaseNodeAttributes defines model for DatabaseNodeAttributes.
type DatabaseNodeAttributes struct {
	Connection string  `json:"connection"`
	Encoding   *string `json:"encoding,omitempty"`
	Engine     string  `json:"engine"`
	File       *string `json:"file,omitempty"`
	IsDefault  bool    `json:"isDefault"`
	PageSize   *int64  `json:"pageSize,omitempty"`
	Sequence   *int    `json:"sequence,omitempty"`
}

// ErrorPayload defines model for ErrorPayload.
type ErrorPayload struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// IndexNode defines model for IndexNode.
type IndexNode struct {
	Attributes IndexNodeAttributes `json:"attributes"`
	Edges      map[string]NodeEdge `json:"edges"`
	Id         string              `json:"id"`
	Name       string              `json:"name"`
	Type       IndexNodeType       `json:"type"`
}

// IndexNodeType defines model for IndexNode.Type.
type IndexNodeType string

// IndexNodeAttributes defines model for IndexNodeAttributes.
type IndexNodeAttributes struct {
	Columns        *[]string `json:"columns,omitempty"`
	Connection     string    `json:"connection"`
	Definition     *string   `json:"definition,omitempty"`
	IncludeColumns *[]string `json:"includeColumns,omitempty"`
	IndexName      string    `json:"indexName"`
	Method         *string   `json:"method,omitempty"`
	Predicate      *string   `json:"predicate,omitempty"`
	Primary        bool      `json:"primary"`
	Table          string    `json:"table"`
	Unique         bool      `json:"unique"`
}

// Node defines model for Node.
type Node struct {
	union json.RawMessage
}

// NodeBase defines model for NodeBase.
type NodeBase struct {
	Edges map[string]NodeEdge `json:"edges"`
	Id    string              `json:"id"`
	Name  string              `json:"name"`
}

// NodeEdge defines model for NodeEdge.
type NodeEdge struct {
	Items     []string `json:"items"`
	Truncated bool     `json:"truncated"`
}

// NodesResponse defines model for NodesResponse.
type NodesResponse struct {
	Nodes []Node `json:"nodes"`
}

// PasswordConfig defines model for PasswordConfig.
type PasswordConfig struct {
	// Key Provider-specific identifier (plain text value, shell command, or keychain account)
	Key string `json:"key"`

	// Type Password provider type
	Type PasswordConfigType `json:"type"`
}

// PasswordConfigType Password provider type
type PasswordConfigType string

// QueryExecOptions defines model for QueryExecOptions.
type QueryExecOptions struct {
	MaxRows *int `json:"maxRows,omitempty"`
}

// QueryExecRequest defines model for QueryExecRequest.
type QueryExecRequest struct {
	ConfigurationName string                   `json:"configurationName"`
	JobId             openapi_types.UUID       `json:"jobId"`
	Options           *QueryExecOptions        `json:"options,omitempty"`
	Params            *QueryExecRequest_Params `json:"params,omitempty"`
	Query             string                   `json:"query"`
}

// QueryExecRequestParams0 defines model for .
type QueryExecRequestParams0 map[string]interface{}

// QueryExecRequestParams1 defines model for .
type QueryExecRequestParams1 = []interface{}

// QueryExecRequest_Params defines model for QueryExecRequest.Params.
type QueryExecRequest_Params struct {
	union json.RawMessage
}

// QueryExecResponse defines model for QueryExecResponse.
type QueryExecResponse struct {
	JobId   string                  `json:"jobId"`
	Message *string                 `json:"message"`
	Status  QueryExecResponseStatus `json:"status"`
}

// QueryExecResponseStatus defines model for QueryExecResponse.Status.
type QueryExecResponseStatus string

// QueryResultColumn defines model for QueryResultColumn.
type QueryResultColumn struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

// QueryResultResponse defines model for QueryResultResponse.
type QueryResultResponse struct {
	Columns      []QueryResultColumn `json:"columns"`
	RowCount     int                 `json:"rowCount"`
	Rows         [][]interface{}     `json:"rows"`
	RowsAffected *int                `json:"rowsAffected"`
	Truncated    bool                `json:"truncated"`
}

// SchemaNode defines model for SchemaNode.
type SchemaNode struct {
	Attributes SchemaNodeAttributes `json:"attributes"`
	Edges      map[string]NodeEdge  `json:"edges"`
	Id         string               `json:"id"`
	Name       string               `json:"name"`
	Type       SchemaNodeType       `json:"type"`
}

// SchemaNodeType defines model for SchemaNode.Type.
type SchemaNodeType string

// SchemaNodeAttributes defines model for SchemaNodeAttributes.
type SchemaNodeAttributes struct {
	Connection string `json:"connection"`
	Engine     string `json:"engine"`
	IsDefault  bool   `json:"isDefault"`
}

// TableNode defines model for TableNode.
type TableNode struct {
	Attributes TableNodeAttributes `json:"attributes"`
	Edges      map[string]NodeEdge `json:"edges"`
	Id         string              `json:"id"`
	Name       string              `json:"name"`
	Type       TableNodeType       `json:"type"`
}

// TableNodeType defines model for TableNode.Type.
type TableNodeType string

// TableNodeAttributes defines model for TableNodeAttributes.
type TableNodeAttributes struct {
	Connection string  `json:"connection"`
	Definition *string `json:"definition,omitempty"`
	Table      string  `json:"table"`
	TableType  string  `json:"tableType"`
}

// TlsConfig defines model for TlsConfig.
type TlsConfig struct {
	// CaCertPath CA certificate path
	CaCertPath *string `json:"caCertPath"`

	// CertPath Client certificate path
	CertPath *string `json:"certPath"`

	// KeyPath Client key path
	KeyPath *string `json:"keyPath"`

	// Mode TLS mode (e.g. require, verify-ca, verify-full)
	Mode *string `json:"mode"`
}

// TriggerNode defines model for TriggerNode.
type TriggerNode struct {
	Attributes TriggerNodeAttributes `json:"attributes"`
	Edges      map[string]NodeEdge   `json:"edges"`
	Id         string                `json:"id"`
	Name       string                `json:"name"`
	Type       TriggerNodeType       `json:"type"`
}

// TriggerNodeType defines model for TriggerNode.Type.
type TriggerNodeType string

// TriggerNodeAttributes defines model for TriggerNodeAttributes.
type TriggerNodeAttributes struct {
	Condition    *string   `json:"condition,omitempty"`
	Connection   string    `json:"connection"`
	Definition   *string   `json:"definition,omitempty"`
	EnabledState *string   `json:"enabledState,omitempty"`
	Events       *[]string `json:"events,omitempty"`
	Orientation  string    `json:"orientation"`
	Statement    *string   `json:"statement,omitempty"`
	Table        string    `json:"table"`
	Timing       string    `json:"timing"`
	TriggerName  string    `json:"triggerName"`
}

// ViewNode defines model for ViewNode.
type ViewNode struct {
	Attributes ViewNodeAttributes  `json:"attributes"`
	Edges      map[string]NodeEdge `json:"edges"`
	Id         string              `json:"id"`
	Name       string              `json:"name"`
	Type       ViewNodeType        `json:"type"`
}

// ViewNodeType defines model for ViewNode.Type.
type ViewNodeType string

// ViewNodeAttributes defines model for ViewNodeAttributes.
type ViewNodeAttributes struct {
	Connection string  `json:"connection"`
	Definition *string `json:"definition,omitempty"`
	Table      string  `json:"table"`
	TableType  string  `json:"tableType"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = ErrorPayload

// GetNodesParams defines parameters for GetNodes.
type GetNodesParams struct {
	// NodeId Optional repeated parameter limiting the nodes returned
	NodeId *[]string `form:"nodeId,omitempty" json:"nodeId,omitempty"`
}

// GetQueryResultParams defines parameters for GetQueryResult.
type GetQueryResultParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// StartConnectionJSONRequestBody defines body for StartConnection for application/json ContentType.
type StartConnectionJSONRequestBody = ConnectionRequest

// ExecQueryJSONRequestBody defines body for ExecQuery for application/json ContentType.
type ExecQueryJSONRequestBody = QueryExecRequest

// AsDatabaseNode returns the union data inside the Node as a DatabaseNode
func (t Node) AsDatabaseNode() (DatabaseNode, error) {
	var body DatabaseNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDatabaseNode overwrites any union data inside the Node as the provided DatabaseNode
func (t *Node) FromDatabaseNode(v DatabaseNode) error {
	v.Type = "database"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDatabaseNode performs a merge with any union data inside the Node, using the provided DatabaseNode
func (t *Node) MergeDatabaseNode(v DatabaseNode) error {
	v.Type = "database"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSchemaNode returns the union data inside the Node as a SchemaNode
func (t Node) AsSchemaNode() (SchemaNode, error) {
	var body SchemaNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSchemaNode overwrites any union data inside the Node as the provided SchemaNode
func (t *Node) FromSchemaNode(v SchemaNode) error {
	v.Type = "schema"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSchemaNode performs a merge with any union data inside the Node, using the provided SchemaNode
func (t *Node) MergeSchemaNode(v SchemaNode) error {
	v.Type = "schema"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTableNode returns the union data inside the Node as a TableNode
func (t Node) AsTableNode() (TableNode, error) {
	var body TableNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTableNode overwrites any union data inside the Node as the provided TableNode
func (t *Node) FromTableNode(v TableNode) error {
	v.Type = "table"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTableNode performs a merge with any union data inside the Node, using the provided TableNode
func (t *Node) MergeTableNode(v TableNode) error {
	v.Type = "table"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsViewNode returns the union data inside the Node as a ViewNode
func (t Node) AsViewNode() (ViewNode, error) {
	var body ViewNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromViewNode overwrites any union data inside the Node as the provided ViewNode
func (t *Node) FromViewNode(v ViewNode) error {
	v.Type = "view"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeViewNode performs a merge with any union data inside the Node, using the provided ViewNode
func (t *Node) MergeViewNode(v ViewNode) error {
	v.Type = "view"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsColumnNode returns the union data inside the Node as a ColumnNode
func (t Node) AsColumnNode() (ColumnNode, error) {
	var body ColumnNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromColumnNode overwrites any union data inside the Node as the provided ColumnNode
func (t *Node) FromColumnNode(v ColumnNode) error {
	v.Type = "column"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeColumnNode performs a merge with any union data inside the Node, using the provided ColumnNode
func (t *Node) MergeColumnNode(v ColumnNode) error {
	v.Type = "column"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsConstraintNode returns the union data inside the Node as a ConstraintNode
func (t Node) AsConstraintNode() (ConstraintNode, error) {
	var body ConstraintNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConstraintNode overwrites any union data inside the Node as the provided ConstraintNode
func (t *Node) FromConstraintNode(v ConstraintNode) error {
	v.Type = "constraint"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConstraintNode performs a merge with any union data inside the Node, using the provided ConstraintNode
func (t *Node) MergeConstraintNode(v ConstraintNode) error {
	v.Type = "constraint"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsIndexNode returns the union data inside the Node as a IndexNode
func (t Node) AsIndexNode() (IndexNode, error) {
	var body IndexNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromIndexNode overwrites any union data inside the Node as the provided IndexNode
func (t *Node) FromIndexNode(v IndexNode) error {
	v.Type = "index"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeIndexNode performs a merge with any union data inside the Node, using the provided IndexNode
func (t *Node) MergeIndexNode(v IndexNode) error {
	v.Type = "index"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTriggerNode returns the union data inside the Node as a TriggerNode
func (t Node) AsTriggerNode() (TriggerNode, error) {
	var body TriggerNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTriggerNode overwrites any union data inside the Node as the provided TriggerNode
func (t *Node) FromTriggerNode(v TriggerNode) error {
	v.Type = "trigger"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTriggerNode performs a merge with any union data inside the Node, using the provided TriggerNode
func (t *Node) MergeTriggerNode(v TriggerNode) error {
	v.Type = "trigger"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Node) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Node) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "column":
		return t.AsColumnNode()
	case "constraint":
		return t.AsConstraintNode()
	case "database":
		return t.AsDatabaseNode()
	case "index":
		return t.AsIndexNode()
	case "schema":
		return t.AsSchemaNode()
	case "table":
		return t.AsTableNode()
	case "trigger":
		return t.AsTriggerNode()
	case "view":
		return t.AsViewNode()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Node) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Node) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsQueryExecRequestParams0 returns the union data inside the QueryExecRequest_Params as a QueryExecRequestParams0
func (t QueryExecRequest_Params) AsQueryExecRequestParams0() (QueryExecRequestParams0, error) {
	var body QueryExecRequestParams0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQueryExecRequestParams0 overwrites any union data inside the QueryExecRequest_Params as the provided QueryExecRequestParams0
func (t *QueryExecRequest_Params) FromQueryExecRequestParams0(v QueryExecRequestParams0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQueryExecRequestParams0 performs a merge with any union data inside the QueryExecRequest_Params, using the provided QueryExecRequestParams0
func (t *QueryExecRequest_Params) MergeQueryExecRequestParams0(v QueryExecRequestParams0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQueryExecRequestParams1 returns the union data inside the QueryExecRequest_Params as a QueryExecRequestParams1
func (t QueryExecRequest_Params) AsQueryExecRequestParams1() (QueryExecRequestParams1, error) {
	var body QueryExecRequestParams1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQueryExecRequestParams1 overwrites any union data inside the QueryExecRequest_Params as the provided QueryExecRequestParams1
func (t *QueryExecRequest_Params) FromQueryExecRequestParams1(v QueryExecRequestParams1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQueryExecRequestParams1 performs a merge with any union data inside the QueryExecRequest_Params, using the provided QueryExecRequestParams1
func (t *QueryExecRequest_Params) MergeQueryExecRequestParams1(v QueryExecRequestParams1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t QueryExecRequest_Params) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *QueryExecRequest_Params) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListConfigurations request
	ListConfigurations(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetNodes request
	GetNodes(ctx context.Context, configurationName string, params *GetNodesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StartConnectionWithBody request with any body
	StartConnectionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	StartConnection(ctx context.Context, body StartConnectionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StreamEvents request
	StreamEvents(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ExecQueryWithBody request with any body
	ExecQueryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ExecQuery(ctx context.Context, body ExecQueryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CancelQuery request
	CancelQuery(ctx context.Context, jobId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetQueryResult request
	GetQueryResult(ctx context.Context, jobId string, params *GetQueryResultParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListConfigurations(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListConfigurationsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetNodes(ctx context.Context, configurationName string, params *GetNodesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetNodesRequest(c.Server, configurationName, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StartConnectionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStartConnectionRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StartConnection(ctx context.Context, body StartConnectionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStartConnectionRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StreamEvents(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStreamEventsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExecQueryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExecQueryRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExecQuery(ctx context.Context, body ExecQueryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExecQueryRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CancelQuery(ctx context.Context, jobId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCancelQueryRequest(c.Server, jobId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetQueryResult(ctx context.Context, jobId string, params *GetQueryResultParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetQueryResultRequest(c.Server, jobId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListConfigurationsRequest generates requests for ListConfigurations
func NewListConfigurationsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/configurations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetNodesRequest generates requests for GetNodes
func NewGetNodesRequest(server string, configurationName string, params *GetNodesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "configurationName", runtime.ParamLocationPath, configurationName)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/configurations/%s/nodes", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.NodeId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "nodeId", runtime.ParamLocationQuery, *params.NodeId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewStartConnectionRequest calls the generic StartConnection builder with application/json body
func NewStartConnectionRequest(server string, body StartConnectionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewStartConnectionRequestWithBody(server, "application/json", bodyReader)
}

// NewStartConnectionRequestWithBody generates requests for StartConnection with any type of body
func NewStartConnectionRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/connections")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewStreamEventsRequest generates requests for StreamEvents
func NewStreamEventsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/events")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewExecQueryRequest calls the generic ExecQuery builder with application/json body
func NewExecQueryRequest(server string, body ExecQueryJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewExecQueryRequestWithBody(server, "application/json", bodyReader)
}

// NewExecQueryRequestWithBody generates requests for ExecQuery with any type of body
func NewExecQueryRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/queries")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCancelQueryRequest generates requests for CancelQuery
func NewCancelQueryRequest(server string, jobId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "jobId", runtime.ParamLocationPath, jobId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/queries/%s/cancel", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetQueryResultRequest generates requests for GetQueryResult
func NewGetQueryResultRequest(server string, jobId string, params *GetQueryResultParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "jobId", runtime.ParamLocationPath, jobId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/queries/%s/result", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListConfigurationsWithResponse request
	ListConfigurationsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListConfigurationsResponse, error)

	// GetNodesWithResponse request
	GetNodesWithResponse(ctx context.Context, configurationName string, params *GetNodesParams, reqEditors ...RequestEditorFn) (*GetNodesResponse, error)

	// StartConnectionWithBodyWithResponse request with any body
	StartConnectionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*StartConnectionResponse, error)

	StartConnectionWithResponse(ctx context.Context, body StartConnectionJSONRequestBody, reqEditors ...RequestEditorFn) (*StartConnectionResponse, error)

	// StreamEventsWithResponse request
	StreamEventsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*StreamEventsResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// ExecQueryWithBodyWithResponse request with any body
	ExecQueryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExecQueryResponse, error)

	ExecQueryWithResponse(ctx context.Context, body ExecQueryJSONRequestBody, reqEditors ...RequestEditorFn) (*ExecQueryResponse, error)

	// CancelQueryWithResponse request
	CancelQueryWithResponse(ctx context.Context, jobId string, reqEditors ...RequestEditorFn) (*CancelQueryResponse, error)

	// GetQueryResultWithResponse request
	GetQueryResultWithResponse(ctx context.Context, jobId string, params *GetQueryResultParams, reqEditors ...RequestEditorFn) (*GetQueryResultResponse, error)
}

type ListConfigurationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ConfigurationsResponse
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListConfigurationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListConfigurationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetNodesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NodesResponse
	JSON404      *ErrorPayload
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetNodesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetNodesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type StartConnectionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *ConnectionResult
	JSON404      *ErrorPayload
	JSON409      *ErrorPayload
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r StartConnectionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StartConnectionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type StreamEventsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r StreamEventsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StreamEventsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ExecQueryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *QueryExecResponse
	JSON404      *ErrorPayload
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ExecQueryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ExecQueryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CancelQueryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *struct {
		Status string `json:"status"`
	}
	JSON404     *ErrorPayload
	JSONDefault *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r CancelQueryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CancelQueryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetQueryResultResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *QueryResultResponse
	JSON404      *ErrorPayload
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetQueryResultResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetQueryResultResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListConfigurationsWithResponse request returning *ListConfigurationsResponse
func (c *ClientWithResponses) ListConfigurationsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListConfigurationsResponse, error) {
	rsp, err := c.ListConfigurations(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListConfigurationsResponse(rsp)
}

// GetNodesWithResponse request returning *GetNodesResponse
func (c *ClientWithResponses) GetNodesWithResponse(ctx context.Context, configurationName string, params *GetNodesParams, reqEditors ...RequestEditorFn) (*GetNodesResponse, error) {
	rsp, err := c.GetNodes(ctx, configurationName, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetNodesResponse(rsp)
}

// StartConnectionWithBodyWithResponse request with arbitrary body returning *StartConnectionResponse
func (c *ClientWithResponses) StartConnectionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*StartConnectionResponse, error) {
	rsp, err := c.StartConnectionWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStartConnectionResponse(rsp)
}

func (c *ClientWithResponses) StartConnectionWithResponse(ctx context.Context, body StartConnectionJSONRequestBody, reqEditors ...RequestEditorFn) (*StartConnectionResponse, error) {
	rsp, err := c.StartConnection(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStartConnectionResponse(rsp)
}

// StreamEventsWithResponse request returning *StreamEventsResponse
func (c *ClientWithResponses) StreamEventsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*StreamEventsResponse, error) {
	rsp, err := c.StreamEvents(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStreamEventsResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// ExecQueryWithBodyWithResponse request with arbitrary body returning *ExecQueryResponse
func (c *ClientWithResponses) ExecQueryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExecQueryResponse, error) {
	rsp, err := c.ExecQueryWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExecQueryResponse(rsp)
}

func (c *ClientWithResponses) ExecQueryWithResponse(ctx context.Context, body ExecQueryJSONRequestBody, reqEditors ...RequestEditorFn) (*ExecQueryResponse, error) {
	rsp, err := c.ExecQuery(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExecQueryResponse(rsp)
}

// CancelQueryWithResponse request returning *CancelQueryResponse
func (c *ClientWithResponses) CancelQueryWithResponse(ctx context.Context, jobId string, reqEditors ...RequestEditorFn) (*CancelQueryResponse, error) {
	rsp, err := c.CancelQuery(ctx, jobId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCancelQueryResponse(rsp)
}

// GetQueryResultWithResponse request returning *GetQueryResultResponse
func (c *ClientWithResponses) GetQueryResultWithResponse(ctx context.Context, jobId string, params *GetQueryResultParams, reqEditors ...RequestEditorFn) (*GetQueryResultResponse, error) {
	rsp, err := c.GetQueryResult(ctx, jobId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetQueryResultResponse(rsp)
}

// ParseListConfigurationsResponse parses an HTTP response from a ListConfigurationsWithResponse call
func ParseListConfigurationsResponse(rsp *http.Response) (*ListConfigurationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListConfigurationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ConfigurationsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetNodesResponse parses an HTTP response from a GetNodesWithResponse call
func ParseGetNodesResponse(rsp *http.Response) (*GetNodesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetNodesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NodesResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorPayload
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseStartConnectionResponse parses an HTTP response from a StartConnectionWithResponse call
func ParseStartConnectionResponse(rsp *http.Response) (*StartConnectionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StartConnectionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest ConnectionResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorPayload
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorPayload
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseStreamEventsResponse parses an HTTP response from a StreamEventsWithResponse call
func ParseStreamEventsResponse(rsp *http.Response) (*StreamEventsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StreamEventsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseExecQueryResponse parses an HTTP response from a ExecQueryWithResponse call
func ParseExecQueryResponse(rsp *http.Response) (*ExecQueryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ExecQueryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest QueryExecResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorPayload
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseCancelQueryResponse parses an HTTP response from a CancelQueryWithResponse call
func ParseCancelQueryResponse(rsp *http.Response) (*CancelQueryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CancelQueryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest struct {
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorPayload
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetQueryResultResponse parses an HTTP response from a GetQueryResultWithResponse call
func ParseGetQueryResultResponse(rsp *http.Response) (*GetQueryResultResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetQueryResultResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest QueryResultResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorPayload
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
