// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CancelQueryData, CancelQueryErrors, CancelQueryResponses, ExecQueryData, ExecQueryErrors, ExecQueryResponses, GetHealthData, GetHealthErrors, GetHealthResponses, GetNodesData, GetNodesErrors, GetNodesResponses, GetQueryResultData, GetQueryResultErrors, GetQueryResultResponses, ListConfigurationsData, ListConfigurationsErrors, ListConfigurationsResponses, StartConnectionData, StartConnectionErrors, StartConnectionResponses, StreamEventsData, StreamEventsErrors, StreamEventsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health probe
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, GetHealthErrors, ThrowOnError>({ url: '/health', ...options });

/**
 * List saved connection configurations
 */
export const listConfigurations = <ThrowOnError extends boolean = false>(options?: Options<ListConfigurationsData, ThrowOnError>) => (options?.client ?? client).get<ListConfigurationsResponses, ListConfigurationsErrors, ThrowOnError>({ url: '/configurations', ...options });

/**
 * Start (or refresh) a connection session for a configuration
 */
export const startConnection = <ThrowOnError extends boolean = false>(options: Options<StartConnectionData, ThrowOnError>) => (options.client ?? client).post<StartConnectionResponses, StartConnectionErrors, ThrowOnError>({
    url: '/connections',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Fetch schema nodes for a configuration
 */
export const getNodes = <ThrowOnError extends boolean = false>(options: Options<GetNodesData, ThrowOnError>) => (options.client ?? client).get<GetNodesResponses, GetNodesErrors, ThrowOnError>({ url: '/configurations/{configurationName}/nodes', ...options });

/**
 * Execute a SQL query asynchronously
 */
export const execQuery = <ThrowOnError extends boolean = false>(options: Options<ExecQueryData, ThrowOnError>) => (options.client ?? client).post<ExecQueryResponses, ExecQueryErrors, ThrowOnError>({
    url: '/queries',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Cancel a running query job
 */
export const cancelQuery = <ThrowOnError extends boolean = false>(options: Options<CancelQueryData, ThrowOnError>) => (options.client ?? client).post<CancelQueryResponses, CancelQueryErrors, ThrowOnError>({ url: '/queries/{jobId}/cancel', ...options });

/**
 * Retrieve a previously stored query result view
 */
export const getQueryResult = <ThrowOnError extends boolean = false>(options: Options<GetQueryResultData, ThrowOnError>) => (options.client ?? client).get<GetQueryResultResponses, GetQueryResultErrors, ThrowOnError>({ url: '/queries/{jobId}/result', ...options });

/**
 * Subscribe to server-sent events for connection and query notifications
 */
export const streamEvents = <ThrowOnError extends boolean = false>(options?: Options<StreamEventsData, ThrowOnError>) => (options?.client ?? client).sse.get<StreamEventsResponses, StreamEventsErrors, ThrowOnError>({ url: '/events', ...options });
