// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CancelQueryData, CancelQueryErrors, CancelQueryResponses, ConnectResourceData, ConnectResourceErrors, ConnectResourceResponses, ExecQueryData, ExecQueryErrors, ExecQueryResponses, GetHealthData, GetHealthErrors, GetHealthResponses, GetNodesData, GetNodesErrors, GetNodesResponses, GetQueryResultData, GetQueryResultErrors, GetQueryResultResponses, ListResourcesData, ListResourcesErrors, ListResourcesResponses, StreamEventsData, StreamEventsErrors, StreamEventsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health probe
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, GetHealthErrors, ThrowOnError>({ url: '/health', ...options });

/**
 * List saved resource definitions
 */
export const listResources = <ThrowOnError extends boolean = false>(options?: Options<ListResourcesData, ThrowOnError>) => (options?.client ?? client).get<ListResourcesResponses, ListResourcesErrors, ThrowOnError>({ url: '/resources', ...options });

/**
 * Start (or refresh) a resource session for a resource
 */
export const connectResource = <ThrowOnError extends boolean = false>(options: Options<ConnectResourceData, ThrowOnError>) => (options.client ?? client).post<ConnectResourceResponses, ConnectResourceErrors, ThrowOnError>({
    url: '/resources/connect',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Fetch schema nodes for a resource
 */
export const getNodes = <ThrowOnError extends boolean = false>(options: Options<GetNodesData, ThrowOnError>) => (options.client ?? client).get<GetNodesResponses, GetNodesErrors, ThrowOnError>({ url: '/resources/{resourceName}/nodes', ...options });

/**
 * Execute a SQL query asynchronously
 */
export const execQuery = <ThrowOnError extends boolean = false>(options: Options<ExecQueryData, ThrowOnError>) => (options.client ?? client).post<ExecQueryResponses, ExecQueryErrors, ThrowOnError>({
    url: '/queries',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Cancel a running query job
 */
export const cancelQuery = <ThrowOnError extends boolean = false>(options: Options<CancelQueryData, ThrowOnError>) => (options.client ?? client).post<CancelQueryResponses, CancelQueryErrors, ThrowOnError>({ url: '/queries/{jobId}/cancel', ...options });

/**
 * Retrieve a previously stored query result view
 */
export const getQueryResult = <ThrowOnError extends boolean = false>(options: Options<GetQueryResultData, ThrowOnError>) => (options.client ?? client).get<GetQueryResultResponses, GetQueryResultErrors, ThrowOnError>({ url: '/queries/{jobId}/result', ...options });

/**
 * Subscribe to server-sent events for resource and query notifications
 */
export const streamEvents = <ThrowOnError extends boolean = false>(options?: Options<StreamEventsData, ThrowOnError>) => (options?.client ?? client).sse.get<StreamEventsResponses, StreamEventsErrors, ThrowOnError>({ url: '/events', ...options });
