---
name: "Setup Docker"

inputs:
  os:
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Docker
      if: inputs.os != 'macos-latest'
      uses: docker/setup-docker-action@v5
    - name: Setup Docker (Macos)
      if: inputs.os == 'macos-latest'
      run: brew install --cask docker && open -a Docker
      shell: bash
