version: 2

run:
  timeout: 3m
  tests: true

formatters:
  enable:
    - gofumpt
    - goimports

formatters-settings:
  gofumpt:
    extra-rules: true
  goimports:
    local-prefixes: github.com/crueladdict/ori

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - errcheck
    - unused
    - unconvert
    - revive
    - gocritic

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
