---
name: "Make action"
inputs:
  action:
    required: true
runs:
  using: "composite"
  steps:
    - run: echo $PATH
    - run: ls -laF /Users/runner/hostedtoolcache/go/
    - run: make ${{ inputs.action }}
      shell: bash
