---
name: "Make action"
inputs:
  action:
    required: true
runs:
  using: "composite"
  steps:
    - name: Check Go
      run: |
        which go
        go version
      shell: bash
    - run: make ${{ inputs.action }}
      shell: bash
