---
name: "Init"
runs:
  using: "composite"
  steps:
    - name: Show info
      run: echo "Triggered by ${{ github.event_name }} by ${{ github.actor }}"
      shell: bash
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.24"
    - name: Add Go 1.24 to PATH
      run: echo "/Users/runner/hostedtoolcache/go/1.24.13/arm64/bin" >> $PATH
      shell: bash
