---
name: "Init info"
inputs:
  runner:
    default: "macos-latest"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Show info
      run: echo "Triggered by ${{ github.event_name }} by ${{ github.actor }}"
      shell: bash
