---
name: Github pipeline
on: [push]
jobs:
  unit-test:
    runs-on: macos-latest
    steps:
      - name: Download Registry
        uses: actions/checkout@v4
      - uses: ./.github/actions/init
      - name: Build
        run: make build
      - name: Backend Test
        run: make test -C apps/ori-be
      - name: TUI Test
        run: bun test apps/ori-tui
