---
name: Github pipeline
on: [push]
jobs:
  unit-test:
    runs-on: macos-latest
    steps:
      - name: Download Registry
        uses: actions/checkout@v4
      - uses: ./.github/actions/init
      - name: Make Build
        uses: ./.github/actions/make
        with:
          action: build
      - name: Make Test
        uses: ./.github/actions/make
        with:
          action: test
