---
name: Github pipeline
on: [push]
jobs:
  init:
    runs-on: macos-latest
    steps:
      - uses: ./.github/actions/init
  build:
    needs: init
    runs-on: macos-latest
    steps:
      - uses: ./.github/actions/make
        with:
          action: build
  test:
    needs: init
    runs-on: macos-latest
    steps:
      - uses: ./.github/actions/make
        with:
          action: test
